#!/bin/bash
set -euo pipefail

HT=../htdocs/

[ -d $HT/docs ] || mkdir -p $HT/docs

cat top.tmpl index.tmpl bottom.tmpl | sed -e 's:_PRE_::g' >$HT/index.html
cat top.tmpl about.tmpl bottom.tmpl | grep -v '<meta' | sed -e 's:_PRE_:About - :g' >$HT/about.html

for x in commonprimes debian dsa fermat keypair publicprivate roca exponent keysize; do
	echo page $x
	title=$(grep '<h3>' $x.tmpl | sed -e 's:<h3>::g' -e 's:</h3>::g')
	cat top.tmpl $x.tmpl | grep -v '<script' | grep -v '<meta' | sed -e "s:_PRE_:$title - :g" >$HT/docs/$x.html
	echo "</div></div>" >>$HT/docs/$x.html
done

echo "All done"
