#!/bin/bash
set -euo pipefail

HT=../htdocs/
HOST="badkeys.info"

[ -d $HT/docs ] || mkdir -p $HT/docs

cat top.tmpl index.tmpl bottom.tmpl |
	sed -e 's:_PRE_::g' \
		-e 's!</head>!<link rel="canonical" href="https://'$HOST'/"></head>!g' \
		>$HT/index.html
cat top.tmpl about.tmpl bottom.tmpl | grep -v '<meta property' | sed -e 's:_PRE_:About - :g' >$HT/about.html
cat top.tmpl submitkey.tmpl bottom.tmpl | grep -v '<meta property' | sed -e 's:_PRE_:Submit Private Key - :g' >$HT/submitkey.html

for x in commonprimes debian dsa fermat keypair publicprivate roca smalld exponent keysize forti; do
	echo page $x
	title=$(grep '<h2>' $x.tmpl | sed -e 's:<h2>::g' -e 's:</h2>::g')
	cat top.tmpl $x.tmpl | grep -v '<script' | grep -v '<meta property' |
		sed -e "s:_PRE_:$title - :g" \
			-e 's!</head>!<link rel="canonical" href="https://'$HOST'/docs/'$x'.html"></head>!g' \
			>$HT/docs/$x.html
	echo "</main></body></html>" >>$HT/docs/$x.html
done

cat "$HT/css/milligreen.css" "$HT/css/bk.css" | cssmin | \
	sed -e 's:calc(100%+2.0rem):calc(100% + 2.0rem):g' >"$HT/css/all.css"

echo "All done"
